### ISSUE TITLE
conveyord is not forking

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#1]
Running: ./conveyord -c conveyor-user.conf does not return and acts the same as ./conveyord -c conveyor-user.conf --nofork

**Comment by msamsonoff** [comment]
I have seen two reasons that cause conveyord to not fork:
1. It does not fork on Windows because the python-daemon package doesn't work on Windows.
2. The virtualenv is not activated.

Cause 1 will be fixed as part of the platform integration.

Cause 2 can be fixed by running the setup.sh script and then sourcing the virtualenv/bin/activate script.

But, please let me know if you've run into another cause of this.

**Comment by tbuser** [comment]
That was the problem, I didn't realize you had to actually run it through virtualenv

**Comment by msamsonoff** [comment]
Resolved.
